 spring:
  datasource:
    url: jdbc:mysql://62.72.19.105:3306/amaclinic_DB
    username: amaclinic
    password: amaclinic2024@;
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
 server:
   servlet:
     context-path: /api
   port: 8080
